name: CI/CD Pipeline for Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t mongisaad/micro1:latest -f ./M1/Dockerfile ./M1
      
      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: mongisaad
          DOCKER_PASSWORD: ${{ secrets.mongisaad }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u mongisaad --password-stdin
          docker push mongisaad/micro1:latest
